require 'Items/ProceduralDistributions'

local function STFRPreDistributionMerge()

	ProceduralDistributions.list.LockerSheriffRosewood = {
		rolls = 4,
		items = {
			"Disc_Retail", 2,
			"Earbuds", 1,
			"Headphones", 1,
			"Radio.CDplayer", 2,
			"Lunchbox", 1,
			"Lunchbox2", 1,
			"Glasses_Aviators", 1,
			"STFR.Hat_Crash_Helmet_Sheriff_Rosewood", 1.5,
			"STFR.Trousers_Sheriff_Rosewood_Crash", 2,
			"Hat_EarMuff_Protectors", 1,
			"Nightstick", 2,
			"Radio.WalkieTalkie4", 1,
			"Shoes_Black", 6,
			"Shoes_Brown", 6,
			"STFR.Hat_Riot_Helmet_Sheriff_Rosewood", 1.5,
			"STFR.Gloves_Riot_Leather_Black", 2,
			"STFR.Gloves_Riot_Leather_Brown", 2,
			"STFR.Gloves_Dress_White", 1,
			"STFR.Jacket_Dress_Sheriff_Rosewood_Officer", 2,
			"STFR.Jacket_Dress_Sheriff_Rosewood_SGT", 1,
			"STFR.Jacket_Dress_Sheriff_Rosewood_CPT", 1,
			"STFR.Vest_HighViz_Sheriff_Yellow", 2,
			"STFR.Vest_HighViz_Sheriff_Green", 2,
			"STFR.Vest_HighViz_Sheriff_Orange", 2,
			"STFR.Bag_DuffelBag_Sheriff_Rosewood", 0.5,
			"STFR.Bag_DuffelBag_Sheriff_Rosewood", 0.5,
			"STFR.Bag_DuffelBag_Sheriff_Rosewood", 0.5,
			"STFR.Hat_Sheriff_Rosewood_Officer", 4,
			"STFR.Hat_Sheriff_Rosewood_SGT", 3,
			"STFR.Hat_Sheriff_Rosewood_CPT", 3,
			"STFR.Jacket_Sheriff_Rosewood_Officer", 4,
			"STFR.Jacket_Sheriff_Rosewood_SGT", 3,
			"STFR.Jacket_Sheriff_Rosewood_CPT", 3,
			"STFR.Shirt_Sheriff_Rosewood_Officer", 8,
			"STFR.Shirt_Sheriff_Rosewood_SGT", 7,
			"STFR.Shirt_Sheriff_Rosewood_CPT", 7,
			"STFR.TShirt_Sheriff_Rosewood_Officer", 8,
			"STFR.TShirt_Sheriff_Rosewood_SGT", 7,
			"STFR.TShirt_Sheriff_Rosewood_CPT", 7,
			"STFR.Necklace_Badge_Sheriff_Rosewood_Gold", 8,
			"STFR.Necklace_Badge_Sheriff_Rosewood_Gold", 8,
			"STFR.Necklace_Badge_Sheriff_Rosewood_Silver", 8,
			"STFR.Necklace_Badge_Sheriff_Rosewood_Silver", 8,
			"STFR.Trousers_Sheriff_Rosewood", 6,
			"STFR.Tie_Full_Sheriff_Rosewood", 2,
			"STFR.Tie_Worn_Sheriff_Rosewood", 2,
			"STFR.Belt_Police_Duty", 2,
			"STFR.Chest_Walkie", 2,
			"STFR.Vest_BulletPolice_Meade", 1,
		},
		junk = {
			rolls = 1,
			items = {
			
			}
		}
	}

	ProceduralDistributions.list.LockerSheriffRosewoodSWAT = {
		rolls = 16,
		items = {
			"Disc_Retail", 2,
			"Earbuds", 1,
			"Headphones", 1,
			"Radio.CDplayer", 2,
			"Lunchbox", 1,
			"Lunchbox2", 1,
			"Glasses_Aviators", 1,
			"Nightstick", 2,
			"Radio.WalkieTalkie4", 1,
			"Shoes_ArmyBoots", 6,
			"Shoes_ArmyBoots", 6,
			"STFR.Hat_Balaclava_SWAT_Face", 1,
			"STFR.STFR_Hat_Balaclava_SWAT_Full", 1,
			"STFR.Glasses_SafetyGoggles_SWAT_Black", 1,
			"STFR.Bag_DuffelBag_Sheriff_Rosewood_SWAT_Green", 0.5,
			"STFR.Bag_DuffelBag_Sheriff_Rosewood_SWAT_Green", 0.5,
			"STFR.Alicepack_Sheriff_Rosewood_SWAT_Green", 0.5,
			"STFR.Hat_Helmet_Sheriff_Rosewood_Officer_SWAT_Green", 1.5,
			"STFR.Gloves_Riot_Leather_Black", 2,
			"STFR.Gloves_Riot_Leather_Brown", 2,
			"STFR.Vest_Tactical_Sheriff_Rosewood_SWAT_Green", 1,
			"STFR.Vest_Tactical_Sheriff_Rosewood_SWAT_Orange", 1,
			"STFR.Vest_BulletSheriff_Rosewood_SWAT_Green", 1,
			"STFR.Hat_BonnieHat_Sheriff_Rosewood_Officer_SWAT_Green", 4,
			"STFR.Hat_BaseballCap_Sheriff_Rosewood_Officer_SWAT_Green", 4,
			"STFR.Hat_BaseballCap_Sheriff_Rosewood_Officer_SWAT_Orange", 2,
			"STFR.Hat_HardHat_Sheriff_Rosewood_SWAT_Orange", 1.5,
			"STFR.Shirt_Sheriff_Rosewood_Officer_SWAT_Green", 10,
			"STFR.TShirt_Sheriff_Rosewood_Officer_SWAT_Green", 10,
			"STFR.Trousers_Sheriff_Rosewood_SWAT_Green", 8,
			"STFR.Belt_Police_Duty", 2,
			"STFR.Chest_Walkie", 2,
		},
		junk = {
			rolls = 1,
			items = {
			
			}
		}
	}

	ProceduralDistributions.list.LockerPoliceMuldraugh = {
		rolls = 16,
		items = {
			"Disc_Retail", 2,
			"Earbuds", 1,
			"Headphones", 1,
			"Radio.CDplayer", 2,
			"Lunchbox", 1,
			"Lunchbox2", 1,
			"Glasses_Aviators", 1,
			"STFR.Hat_Crash_Helmet_Police_Muldraugh", 1.5,
			"STFR.Trousers_Police_Muldraugh_Crash", 2,
			"Hat_EarMuff_Protectors", 1,
			"Nightstick", 2,
			"Radio.WalkieTalkie4", 1,
			"Shoes_Black", 6,
			"Shoes_Brown", 6,
			"STFR.Hat_Riot_Helmet_Police_Muldraugh", 1.5,
			"STFR.Gloves_Riot_Leather_Black", 2,
			"STFR.Gloves_Riot_Leather_Brown", 2,
			"STFR.Gloves_Dress_White", 1,
			"STFR.Jacket_Dress_Police_Muldraugh_Officer", 2,
			"STFR.Jacket_Dress_Police_Muldraugh_SGT", 1,
			"STFR.Jacket_Dress_Police_Muldraugh_CPT", 1,
			"STFR.Vest_HighViz_Police_Yellow", 2,
			"STFR.Vest_HighViz_Police_Green", 2,
			"STFR.Vest_HighViz_Police_Green_Unmarked", 2,
			"STFR.Bag_DuffelBag_Police_Black", 0.5,
			"STFR.Bag_DuffelBag_Police_Navy", 0.5,
			"STFR.Bag_DuffelBag_Police_Olive", 0.5,
			"STFR.Hat_Police_Muldraugh_Officer", 4,
			"STFR.Hat_Police_Muldraugh_SGT", 3,
			"STFR.Hat_Police_Muldraugh_CPT", 3,
			"STFR.Jacket_Police_Muldraugh_Officer", 4,
			"STFR.Jacket_Police_Muldraugh_SGT", 3,
			"STFR.Jacket_Police_Muldraugh_CPT", 3,
			"STFR.Shirt_Police_Muldraugh_Officer", 8,
			"STFR.Shirt_Police_Muldraugh_SGT", 7,
			"STFR.Shirt_Police_Muldraugh_CPT", 7,
			"STFR.TShirt_Police_Muldraugh_Officer", 8,
			"STFR.TShirt_Police_Muldraugh_SGT", 7,
			"STFR.TShirt_Police_Muldraugh_CPT", 7,
			"STFR.Necklace_Badge_Police_Muldraugh_Gold", 8,
			"STFR.Necklace_Badge_Police_Muldraugh_Gold", 8,
			"STFR.Necklace_Badge_Police_Muldraugh_Silver", 8,
			"STFR.Necklace_Badge_Police_Muldraugh_Silver", 8,
			"STFR.Trousers_Police_Muldraugh", 6,
			"STFR.Tie_Full_Police_Muldraugh", 2,
			"STFR.Tie_Worn_Police_Muldraugh", 2,
			"STFR.Belt_Police_Duty", 2,
			"STFR.Chest_Walkie", 2,
			"Vest_BulletPolice", 1,
		},
		junk = {
			rolls = 1,
			items = {
			
			}
		}
	}

	ProceduralDistributions.list.LockerSheriffMeade = {
		rolls = 16,
		items = {
			"Disc_Retail", 2,
			"Earbuds", 1,
			"Headphones", 1,
			"Radio.CDplayer", 2,
			"Lunchbox", 1,
			"Lunchbox2", 1,
			"Glasses_Aviators", 1,
			"STFR.Hat_Crash_Helmet_Sheriff_Meade", 1.5,
			"STFR.Trousers_Sheriff_Meade_Crash", 2,
			"Hat_EarMuff_Protectors", 1,
			"Nightstick", 2,
			"Radio.WalkieTalkie4", 1,
			"Shoes_Black", 6,
			"Shoes_Brown", 6,
			"STFR.Hat_Riot_Helmet_Sheriff_Meade", 1.5,
			"STFR.Hat_Riot_Helmet_Sheriff_Meade_Solid", 1.5,
			"STFR.Hat_Riot_Helmet_Sheriff_Meade_Stripe", 1.5,
			"STFR.Gloves_Riot_Leather_Black", 2,
			"STFR.Gloves_Riot_Leather_Brown", 2,
			"STFR.Gloves_Dress_White", 1,
			"STFR.Jacket_Dress_Sheriff_Meade_Officer", 2,
			"STFR.Jacket_Dress_Sheriff_Meade_SGT", 1,
			"STFR.Jacket_Dress_Sheriff_Meade_CPT", 1,
			"STFR.Vest_HighViz_Sheriff_Yellow", 2,
			"STFR.Vest_HighViz_Sheriff_Green", 2,
			"STFR.Vest_HighViz_Sheriff_Orange", 2,
			"STFR.Bag_DuffelBag_Sheriff_Meade", 0.5,
			"STFR.Bag_DuffelBag_Sheriff_Meade", 0.5,
			"STFR.Bag_DuffelBag_Sheriff_Meade", 0.5,
			"STFR.Hat_Sheriff_Meade_Officer", 4,
			"STFR.Hat_Sheriff_Meade_Officer", 3,
			"STFR.Hat_Sheriff_Meade_Officer", 3,
			"STFR.Jacket_Sheriff_Meade_Officer", 4,
			"STFR.Jacket_Sheriff_Meade_SGT", 3,
			"STFR.Jacket_Sheriff_Meade_CPT", 3,
			"STFR.Shirt_Sheriff_Meade_Officer", 8,
			"STFR.Shirt_Sheriff_Meade_SGT", 7,
			"STFR.Shirt_Sheriff_Meade_CPT", 7,
			"STFR.TShirt_Sheriff_Meade_Officer", 8,
			"STFR.TShirt_Sheriff_Meade_SGT", 7,
			"STFR.TShirt_Sheriff_Meade_CPT", 7,
			"STFR.Necklace_Badge_Sheriff_Meade_Gold", 8,
			"STFR.Necklace_Badge_Sheriff_Meade_Gold", 8,
			"STFR.Necklace_Badge_Sheriff_Meade_Gold", 8,
			"STFR.Necklace_Badge_Sheriff_Meade_Gold", 8,
			"STFR.Trousers_Sheriff_Meade", 6,
			"STFR.Tie_Full_Sheriff_Meade", 2,
			"STFR.Tie_Worn_Sheriff_Meade", 2,
			"STFR.Belt_Police_Duty", 2,
			"STFR.Chest_Walkie", 2,
			"STFR.Vest_BulletPolice_Meade", 1,
		},
		junk = {
			rolls = 1,
			items = {
			
			}
		}
	}

	ProceduralDistributions.list.LockerSheriffMeadeSWAT = {
		rolls = 16,
		items = {
			"Disc_Retail", 2,
			"Earbuds", 1,
			"Headphones", 1,
			"Radio.CDplayer", 2,
			"Lunchbox", 1,
			"Lunchbox2", 1,
			"Glasses_Aviators", 1,
			"Nightstick", 2,
			"Radio.WalkieTalkie4", 1,
			"Shoes_ArmyBoots", 6,
			"Shoes_ArmyBoots", 6,
			"STFR.Hat_Balaclava_SWAT_Face", 1,
			"STFR.STFR_Hat_Balaclava_SWAT_Full", 1,
			"STFR.Glasses_SafetyGoggles_SWAT_Black", 1,
			"STFR.Bag_DuffelBag_Sheriff_Meade_SWAT_Tan", 0.5,
			"STFR.Bag_DuffelBag_Sheriff_Meade_SWAT_Tan", 0.5,
			"STFR.Alicepack_Sheriff_Meade_SWAT_Tan", 0.5,
			"STFR.Hat_Helmet_Sheriff_Meade_Officer_SWAT_Tan", 1.5,
			"STFR.Hat_Helmet_Sheriff_Meade_Officer_SWAT_Tan", 1.5,
			"STFR.Gloves_Riot_Leather_Black", 2,
			"STFR.Gloves_Riot_Leather_Brown", 2,
			"STFR.Vest_Tactical_Sheriff_Meade_SWAT_Tan", 1,
			"STFR.Vest_Tactical_Sheriff_Meade_SWAT_Tan", 1,
			"STFR.Vest_BulletSheriff_Meade_SWAT_Tan", 1,
			"STFR.Hat_BonnieHat_Sheriff_Meade_Officer_SWAT_Tan", 4,
			"STFR.Hat_BaseballCap_Sheriff_Meade_Officer_SWAT_Tan", 4,
			"STFR.Hat_BaseballCap_Sheriff_Meade_Officer_SWAT_Tan", 2,
			"STFR.Shirt_Sheriff_Meade_Officer_SWAT_Tan", 10,
			"STFR.TShirt_Sheriff_Meade_Officer_SWAT_Tan", 10,
			"STFR.Trousers_Sheriff_Meade_SWAT_Tan", 8,
			"STFR.Belt_Police_Duty", 2,
			"STFR.Chest_Walkie", 2,
		},
		junk = {
			rolls = 1,
			items = {
			
			}
		}
	}

	ProceduralDistributions.list.LockerPoliceWestPoint = {
		rolls = 8,
		items = {
			"Disc_Retail", 2,
			"Earbuds", 1,
			"Headphones", 1,
			"Radio.CDplayer", 2,
			"Lunchbox", 1,
			"Lunchbox2", 1,
			"Glasses_Aviators", 1,
			"STFR.Hat_Crash_Helmet_Police_WestPoint", 1.5,
			"STFR.Trousers_Police_WestPoint_Crash", 2,
			"Hat_EarMuff_Protectors", 1,
			"Nightstick", 2,
			"Radio.WalkieTalkie4", 1,
			"Shoes_Black", 6,
			"Shoes_Brown", 6,
			"STFR.Hat_Riot_Helmet_Police_WestPoint", 1.5,
			"STFR.Gloves_Riot_Leather_Black", 2,
			"STFR.Gloves_Riot_Leather_Brown", 2,
			"STFR.Gloves_Dress_White", 1,
			"STFR.Jacket_Dress_Police_WestPoint_Officer", 2,
			"STFR.Jacket_Dress_Police_WestPoint_SGT", 1,
			"STFR.Jacket_Dress_Police_WestPoint_CPT", 1,
			"STFR.Vest_HighViz_Police_Yellow", 2,
			"STFR.Vest_HighViz_Police_Green", 2,
			"STFR.Vest_HighViz_Police_Green_Unmarked", 2,
			"STFR.Bag_DuffelBag_Police_Black", 0.5,
			"STFR.Bag_DuffelBag_Police_Navy", 0.5,
			"STFR.Bag_DuffelBag_Police_Olive", 0.5,
			"STFR.Hat_Police_WestPoint_Officer", 4,
			"STFR.Hat_Police_WestPoint_SGT", 3,
			"STFR.Hat_Police_WestPoint_CPT", 3,
			"STFR.Jacket_Police_WestPoint_Officer", 4,
			"STFR.Jacket_Police_WestPoint_SGT", 3,
			"STFR.Jacket_Police_WestPoint_CPT", 3,
			"STFR.Shirt_Police_WestPoint_Officer", 8,
			"STFR.Shirt_Police_WestPoint_SGT", 7,
			"STFR.Shirt_Police_WestPoint_CPT", 7,
			"STFR.TShirt_Police_WestPoint_Officer", 8,
			"STFR.TShirt_Police_WestPoint_SGT", 7,
			"STFR.TShirt_Police_WestPoint_CPT", 7,
			"STFR.Necklace_Badge_Police_WestPoint_Gold", 8,
			"STFR.Necklace_Badge_Police_WestPoint_Gold", 8,
			"STFR.Necklace_Badge_Police_WestPoint_Silver", 8,
			"STFR.Necklace_Badge_Police_WestPoint_Silver", 8,
			"STFR.Trousers_Police_WestPoint", 6,
			"STFR.Tie_Full_Police_WestPoint", 2,
			"STFR.Tie_Worn_Police_WestPoint", 2,
			"STFR.Belt_Police_Duty", 2,
			"STFR.Chest_Walkie", 2,
			"Vest_BulletPolice", 1,
		},
		junk = {
			rolls = 1,
			items = {
			
			}
		}
	}

	ProceduralDistributions.list.LockerPoliceWestPointSWAT = {
		rolls = 16,
		items = {
			"Disc_Retail", 2,
			"Earbuds", 1,
			"Headphones", 1,
			"Radio.CDplayer", 2,
			"Lunchbox", 1,
			"Lunchbox2", 1,
			"Glasses_Aviators", 1,
			"Nightstick", 2,
			"Radio.WalkieTalkie4", 1,
			"Shoes_ArmyBoots", 6,
			"Shoes_ArmyBoots", 6,
			"STFR.Hat_Balaclava_SWAT_Face", 1,
			"STFR.STFR_Hat_Balaclava_SWAT_Full", 1,
			"STFR.Glasses_SafetyGoggles_SWAT_Black", 1,
			"STFR.Bag_DuffelBag_Police_WestPoint_SWAT_Navy", 0.5,
			"STFR.Bag_DuffelBag_Police_WestPoint_SWAT_Navy", 0.5,
			"STFR.Alicepack_Police_WestPoint_SWAT_Navy", 0.5,
			"STFR.Hat_Helmet_Police_WestPoint_Officer_SWAT_Black", 1.5,
			"STFR.Hat_Helmet_Police_WestPoint_Officer_SWAT_Black", 1.5,
			"STFR.Gloves_Riot_Leather_Black", 2,
			"STFR.Gloves_Riot_Leather_Brown", 2,
			"STFR.Vest_Tactical_Police_WestPoint_SWAT_Black", 1,
			"STFR.Vest_Tactical_Police_WestPoint_SWAT_Black", 1,
			"STFR.Vest_BulletPolice_WestPoint_SWAT_Black", 1,
			"STFR.Hat_BonnieHat_Police_WestPoint_Officer_SWAT_Navy", 4,
			"STFR.Hat_BaseballCap_Police_WestPoint_Officer_SWAT_Navy", 4,
			"STFR.Hat_BaseballCap_Police_WestPoint_Officer_SWAT_Navy", 2,
			"STFR.Shirt_Police_WestPoint_Officer_SWAT_Navy", 10,
			"STFR.TShirt_Police_WestPoint_Officer_SWAT_Navy", 10,
			"STFR.Trousers_Police_WestPoint_SWAT_Navy", 8,
			"STFR.Belt_Police_Duty", 2,
			"STFR.Chest_Walkie", 2,
		},
		junk = {
			rolls = 1,
			items = {
			
			}
		}
	}

	ProceduralDistributions.list.LockerPoliceRiverside = {
		rolls = 16,
		items = {
			"Disc_Retail", 2,
			"Earbuds", 1,
			"Headphones", 1,
			"Radio.CDplayer", 2,
			"Lunchbox", 1,
			"Lunchbox2", 1,
			"Glasses_Aviators", 1,
			"STFR.Hat_Crash_Helmet_Police_Riverside", 1.5,
			"STFR.Trousers_Police_Riverside_Crash", 2,
			"Hat_EarMuff_Protectors", 1,
			"Nightstick", 2,
			"Radio.WalkieTalkie4", 1,
			"Shoes_Black", 6,
			"Shoes_Brown", 6,
			"STFR.Hat_Riot_Helmet_Police_Riverside", 1.5,
			"STFR.Hat_Riot_Helmet_Police_Riverside_Stripe", 1.5,
			"STFR.Gloves_Riot_Leather_Black", 2,
			"STFR.Gloves_Riot_Leather_Brown", 2,
			"STFR.Gloves_Dress_White", 1,
			"STFR.Jacket_Dress_Police_Riverside_Officer", 2,
			"STFR.Jacket_Dress_Police_Riverside_SGT", 1,
			"STFR.Jacket_Dress_Police_Riverside_CPT", 1,
			"STFR.Vest_HighViz_Police_Riverside", 2,
			"STFR.Vest_HighViz_Police_Riverside", 2,
			"STFR.Vest_HighViz_Police_Riverside", 2,
			"STFR.Bag_DuffelBag_Police_Black", 0.5,
			"STFR.Bag_DuffelBag_Police_Navy", 0.5,
			"STFR.Bag_DuffelBag_Police_Olive", 0.5,
			"STFR.Hat_Police_Riverside_Officer", 4,
			"STFR.Hat_Police_Riverside_SGT", 3,
			"STFR.Hat_Police_Riverside_CPT", 3,
			"STFR.Jacket_Police_Riverside_Officer", 4,
			"STFR.Jacket_Police_Riverside_SGT", 3,
			"STFR.Jacket_Police_Riverside_CPT", 3,
			"STFR.Shirt_Police_Riverside_Officer", 8,
			"STFR.Shirt_Police_Riverside_SGT", 7,
			"STFR.Shirt_Police_Riverside_CPT", 7,
			"STFR.TShirt_Police_Riverside_Officer", 8,
			"STFR.TShirt_Police_Riverside_SGT", 7,
			"STFR.TShirt_Police_Riverside_CPT", 7,
			"STFR.Necklace_Badge_Police_Riverside_Gold", 8,
			"STFR.Necklace_Badge_Police_Riverside_Gold", 8,
			"STFR.Necklace_Badge_Police_Riverside_Silver", 8,
			"STFR.Necklace_Badge_Police_Riverside_Silver", 8,
			"STFR.Trousers_Police_Riverside", 6,
			"STFR.Tie_Full_Police_Riverside", 2,
			"STFR.Tie_Worn_Police_Riverside", 2,
			"STFR.Belt_Police_Duty", 2,
			"STFR.Chest_Walkie", 2,
			"Vest_BulletPolice", 1,
		},
		junk = {
			rolls = 1,
			items = {
			
			}
		}
	}

	ProceduralDistributions.list.LockerPoliceRiversideSWAT = {
		rolls = 16,
		items = {
			"Disc_Retail", 2,
			"Earbuds", 1,
			"Headphones", 1,
			"Radio.CDplayer", 2,
			"Lunchbox", 1,
			"Lunchbox2", 1,
			"Glasses_Aviators", 1,
			"Nightstick", 2,
			"Radio.WalkieTalkie4", 1,
			"Shoes_ArmyBoots", 6,
			"Shoes_ArmyBoots", 6,
			"STFR.Hat_Balaclava_SWAT_Face", 1,
			"STFR.STFR_Hat_Balaclava_SWAT_Full", 1,
			"STFR.Glasses_SafetyGoggles_SWAT_Black", 1,
			"STFR.Bag_DuffelBag_Police_Riverside_SWAT_Blue", 0.5,
			"STFR.Bag_DuffelBag_Police_Riverside_SWAT_Blue", 0.5,
			"STFR.Gloves_Riot_Leather_Black", 2,
			"STFR.Gloves_Riot_Leather_Brown", 2,
			"STFR.Vest_Tactical_Police_Riverside_SWAT_Blue", 1,
			"STFR.Vest_Tactical_Police_Riverside_SWAT_Orange", 1,
			"STFR.Hat_BonnieHat_Police_Riverside_Officer_SWAT_Blue", 4,
			"STFR.Hat_BaseballCap_Police_Riverside_Officer_SWAT_Blue", 4,
			"STFR.Hat_BaseballCap_Police_Riverside_Officer_SWAT_Blue", 4,
			"STFR.Shirt_Police_Riverside_Officer_SWAT_Blue", 10,
			"STFR.TShirt_Police_Riverside_Officer_SWAT_Blue", 10,
			"STFR.Trousers_Police_Riverside_SWAT_Blue", 8,
			"STFR.Belt_Police_Duty", 2,
			"STFR.Chest_Walkie", 2,
		},
		junk = {
			rolls = 1,
			items = {
			
			}
		}
	}

	ProceduralDistributions.list.LockerPoliceLouisville = {
		rolls = 4,
		items = {
			"Disc_Retail", 2,
			"Earbuds", 1,
			"Headphones", 1,
			"Radio.CDplayer", 2,
			"Lunchbox", 1,
			"Lunchbox2", 1,
			"Glasses_Aviators", 1,
			"STFR.Hat_Crash_Helmet_Police_Louisville", 1.5,
			"STFR.Trousers_Police_Louisville_Crash", 2,
			"Hat_EarMuff_Protectors", 1,
			"Nightstick", 2,
			"Radio.WalkieTalkie4", 1,
			"Shoes_Black", 6,
			"Shoes_Brown", 6,
			"STFR.Hat_Riot_Helmet_Police_Louisville", 1.5,
			"STFR.Gloves_Riot_Leather_Black", 2,
			"STFR.Gloves_Riot_Leather_Brown", 2,
			"STFR.Gloves_Dress_White", 1,
			"STFR.Jacket_Dress_Police_Louisville_Officer", 2,
			"STFR.Jacket_Dress_Police_Louisville_SGT", 1,
			"STFR.Jacket_Dress_Police_Louisville_CPT", 1,
			"STFR.Vest_HighViz_Police_Yellow", 2,
			"STFR.Vest_HighViz_Police_Green", 2,
			"STFR.Vest_HighViz_Police_Green_Unmarked", 2,
			"STFR.Bag_DuffelBag_Police_Black", 0.5,
			"STFR.Bag_DuffelBag_Police_Navy", 0.5,
			"STFR.Bag_DuffelBag_Police_Olive", 0.5,
			"STFR.Hat_Police_Louisville_Officer", 4,
			"STFR.Hat_Police_Louisville_SGT", 3,
			"STFR.Hat_Police_Louisville_CPT", 3,
			"STFR.Jacket_Police_Louisville_Officer", 4,
			"STFR.Jacket_Police_Louisville_SGT", 3,
			"STFR.Jacket_Police_Louisville_CPT", 3,
			"STFR.Shirt_Police_Louisville_Officer", 8,
			"STFR.Shirt_Police_Louisville_SGT", 7,
			"STFR.Shirt_Police_Louisville_CPT", 7,
			"STFR.TShirt_Police_Louisville_Officer", 8,
			"STFR.TShirt_Police_Louisville_SGT", 7,
			"STFR.TShirt_Police_Louisville_CPT", 7,
			"STFR.Necklace_Badge_Police_Louisville_Gold", 8,
			"STFR.Necklace_Badge_Police_Louisville_Gold", 8,
			"STFR.Necklace_Badge_Police_Louisville_Silver", 8,
			"STFR.Necklace_Badge_Police_Louisville_Silver", 8,
			"STFR.Trousers_Police_Louisville", 6,
			"STFR.Tie_Full_Police_Louisville", 2,
			"STFR.Tie_Worn_Police_Louisville", 2,
			"STFR.Belt_Police_Duty", 2,
			"STFR.Chest_Walkie", 2,
			"Vest_BulletPolice", 1,
		},
		junk = {
			rolls = 1,
			items = {
			
			}
		}
	}

	ProceduralDistributions.list.LockerPoliceLouisvilleSWAT = {
		rolls = 16,
		items = {
			"Disc_Retail", 2,
			"Earbuds", 1,
			"Headphones", 1,
			"Radio.CDplayer", 2,
			"Lunchbox", 1,
			"Lunchbox2", 1,
			"Glasses_Aviators", 1,
			"Nightstick", 2,
			"Radio.WalkieTalkie4", 1,
			"Shoes_ArmyBoots", 6,
			"Shoes_ArmyBoots", 6,
			"STFR.Hat_Balaclava_SWAT_Face", 1,
			"STFR.STFR_Hat_Balaclava_SWAT_Full", 1,
			"STFR.Glasses_SafetyGoggles_SWAT_Black", 1,
			"STFR.Bag_DuffelBag_Police_Louisville_SWAT_Black", 0.5,
			"STFR.Bag_DuffelBag_Police_Louisville_SWAT_Black", 0.5,
			"STFR.Alicepack_Police_Louisville_SWAT_Black", 0.5,
			"STFR.Hat_Helmet_Police_Louisville_Officer_SWAT_Black", 1.5,
			"STFR.Hat_Helmet_Police_Louisville_Officer_SWAT_Camo", 1.5,
			"STFR.Gloves_Riot_Leather_Black", 2,
			"STFR.Gloves_Riot_Leather_Brown", 2,
			"STFR.Vest_Tactical_Police_Louisville_SWAT_Black", 1,
			"STFR.Vest_Tactical_Police_Louisville_SWAT_Black", 1,
			"STFR.Vest_BulletPolice_Louisville_SWAT_Black", 1,
			"STFR.Hat_BonnieHat_Police_Louisville_Officer_SWAT_Black", 4,
			"STFR.Hat_BonnieHat_Police_Louisville_Officer_SWAT_Camo", 4,
			"STFR.Hat_BaseballCap_Police_Louisville_Officer_SWAT_Black", 4,
			"STFR.Hat_BaseballCap_Police_Louisville_Officer_SWAT_Camo", 4,
			"STFR.Shirt_Police_Louisville_Officer_SWAT_Black", 10,
			"STFR.Shirt_Police_Louisville_Officer_SWAT_Camo", 10,
			"STFR.TShirt_Police_Louisville_Officer_SWAT_Black", 10,
			"STFR.TShirt_Police_Louisville_Officer_SWAT_Camo", 10,
			"STFR.Trousers_Police_Louisville_SWAT_Black", 8,
			"STFR.Trousers_Police_Louisville_SWAT_Camo", 8,
			"STFR.Belt_Police_Duty", 2,
			"STFR.Chest_Walkie", 2,
		},
		junk = {
			rolls = 1,
			items = {
			
			}
		}
	}

	ProceduralDistributions.list.LockerPoliceJefferson = {
		rolls = 8,
		items = {
			"Disc_Retail", 2,
			"Earbuds", 1,
			"Headphones", 1,
			"Radio.CDplayer", 2,
			"Lunchbox", 1,
			"Lunchbox2", 1,
			"Glasses_Aviators", 1,
			"STFR.Hat_Crash_Helmet_Police_Jefferson", 1.5,
			"STFR.Trousers_Police_Jefferson_Crash", 2,
			"Hat_EarMuff_Protectors", 1,
			"Nightstick", 2,
			"Radio.WalkieTalkie4", 1,
			"Shoes_Black", 6,
			"Shoes_Brown", 6,
			"STFR.Hat_Riot_Helmet_Police_Jefferson", 1.5,
			"STFR.Gloves_Riot_Leather_Black", 2,
			"STFR.Gloves_Riot_Leather_Brown", 2,
			"STFR.Gloves_Dress_White", 1,
			"STFR.Jacket_Dress_Police_Jefferson_Officer", 2,
			"STFR.Jacket_Dress_Police_Jefferson_SGT", 1,
			"STFR.Jacket_Dress_Police_Jefferson_CPT", 1,
			"STFR.Vest_HighViz_Police_Yellow", 2,
			"STFR.Vest_HighViz_Police_Green", 2,
			"STFR.Vest_HighViz_Police_Green_Unmarked", 2,
			"STFR.Bag_DuffelBag_Police_Black", 0.5,
			"STFR.Bag_DuffelBag_Police_Navy", 0.5,
			"STFR.Bag_DuffelBag_Police_Olive", 0.5,
			"STFR.Hat_Police_Jefferson_Officer", 4,
			"STFR.Hat_Police_Jefferson_SGT", 3,
			"STFR.Hat_Police_Jefferson_CPT", 3,
			"STFR.Jacket_Police_Jefferson_Officer", 4,
			"STFR.Jacket_Police_Jefferson_SGT", 3,
			"STFR.Jacket_Police_Jefferson_CPT", 3,
			"STFR.Shirt_Police_Jefferson_Officer", 8,
			"STFR.Shirt_Police_Jefferson_SGT", 7,
			"STFR.Shirt_Police_Jefferson_CPT", 7,
			"STFR.TShirt_Police_Jefferson_Officer", 8,
			"STFR.TShirt_Police_Jefferson_SGT", 7,
			"STFR.TShirt_Police_Jefferson_CPT", 7,
			"STFR.Necklace_Badge_Police_Jefferson_Gold", 8,
			"STFR.Necklace_Badge_Police_Jefferson_Gold", 8,
			"STFR.Necklace_Badge_Police_Jefferson_Silver", 8,
			"STFR.Necklace_Badge_Police_Jefferson_Silver", 8,
			"STFR.Trousers_Police_Jefferson", 6,
			"STFR.Tie_Full_Police_Jefferson", 2,
			"STFR.Tie_Worn_Police_Jefferson", 2,
			"STFR.Belt_Police_Duty", 2,
			"STFR.Chest_Walkie", 2,
			"Vest_BulletPolice", 1,
		},
		junk = {
			rolls = 1,
			items = {
			
			}
		}
	}

	ProceduralDistributions.list.LockerPoliceJeffersonSWAT = {
		rolls = 16,
		items = {
			"Disc_Retail", 2,
			"Earbuds", 1,
			"Headphones", 1,
			"Radio.CDplayer", 2,
			"Lunchbox", 1,
			"Lunchbox2", 1,
			"Glasses_Aviators", 1,
			"Nightstick", 2,
			"Radio.WalkieTalkie4", 1,
			"Shoes_ArmyBoots", 6,
			"Shoes_ArmyBoots", 6,
			"STFR.Hat_Balaclava_SWAT_Face", 1,
			"STFR.STFR_Hat_Balaclava_SWAT_Full", 1,
			"STFR.Glasses_SafetyGoggles_SWAT_Black", 1,
			"STFR.Bag_DuffelBag_Police_Jefferson_SWAT_Blue", 0.5,
			"STFR.Bag_DuffelBag_Police_Jefferson_SWAT_Blue", 0.5,
			"STFR.Alicepack_Police_Jefferson_SWAT_Blue", 0.5,
			"STFR.Helmet_Police_Jefferson_Officer_SWAT_Blue", 1.5,
			"STFR.Helmet_Police_Jefferson_Officer_SWAT_Blue", 1.5,
			"STFR.Gloves_Riot_Leather_Black", 2,
			"STFR.Gloves_Riot_Leather_Brown", 2,
			"STFR.Vest_Tactical_Police_Jefferson_SWAT_Blue", 1,
			"STFR.Vest_Tactical_Police_Jefferson_SWAT_Blue", 1,
			"STFR.Vest_BulletPolice_Jefferson_SWAT_Blue", 1,
			"STFR.Hat_BonnieHat_Police_Jefferson_Officer_SWAT_Blue", 4,
			"STFR.Hat_BaseballCap_Police_Jefferson_Officer_SWAT_Blue", 4,
			"STFR.Hat_BaseballCap_Police_Jefferson_Officer_SWAT_Blue", 2,
			"STFR.Shirt_Police_Jefferson_Officer_SWAT_Blue", 10,
			"STFR.TShirt_Police_Jefferson_Officer_SWAT_Blue", 10,
			"STFR.Trousers_Police_Jefferson_SWAT_Blue", 8,
			"STFR.Belt_Police_Duty", 2,
			"STFR.Chest_Walkie", 2,
		},
		junk = {
			rolls = 1,
			items = {
			
			}
		}
	}

	ProceduralDistributions.list.LockerSheriffJefferson = {
		rolls = 16,
		items = {
			"Disc_Retail", 2,
			"Earbuds", 1,
			"Headphones", 1,
			"Radio.CDplayer", 2,
			"Lunchbox", 1,
			"Lunchbox2", 1,
			"Glasses_Aviators", 1,
			"STFR.Hat_Crash_Helmet_Sheriff_Jefferson", 1.5,
			"STFR.Trousers_Sheriff_Jefferson_Crash", 2,
			"Hat_EarMuff_Protectors", 1,
			"Nightstick", 2,
			"Radio.WalkieTalkie4", 1,
			"Shoes_Black", 6,
			"Shoes_Brown", 6,
			"STFR.Hat_Riot_Helmet_Sheriff_Jefferson", 1.5,
			"STFR.Gloves_Riot_Leather_Black", 2,
			"STFR.Gloves_Riot_Leather_Brown", 2,
			"STFR.Gloves_Dress_White", 1,
			"STFR.Jacket_Dress_Sheriff_Jefferson_Officer", 2,
			"STFR.Jacket_Dress_Sheriff_Jefferson_SGT", 1,
			"STFR.Jacket_Dress_Sheriff_Jefferson_CPT", 1,
			"STFR.Vest_HighViz_Sheriff_Yellow", 2,
			"STFR.Vest_HighViz_Sheriff_Green", 2,
			"STFR.Vest_HighViz_Sheriff_Orange", 2,
			"STFR.Bag_DuffelBag_Sheriff_Jefferson", 0.5,
			"STFR.Bag_DuffelBag_Sheriff_Jefferson", 0.5,
			"STFR.Bag_DuffelBag_Sheriff_Jefferson", 0.5,
			"STFR.Hat_Sheriff_Jefferson_Officer", 4,
			"STFR.Hat_Sheriff_Jefferson_Officer", 3,
			"STFR.Hat_Sheriff_Jefferson_Officer", 3,
			"STFR.Jacket_Sheriff_Jefferson_Officer", 4,
			"STFR.Jacket_Sheriff_Jefferson_SGT", 3,
			"STFR.Jacket_Sheriff_Jefferson_CPT", 3,
			"STFR.Shirt_Sheriff_Jefferson_Officer", 8,
			"STFR.Shirt_Sheriff_Jefferson_SGT", 7,
			"STFR.Shirt_Sheriff_Jefferson_CPT", 7,
			"STFR.TShirt_Sheriff_Jefferson_Officer", 8,
			"STFR.TShirt_Sheriff_Jefferson_SGT", 7,
			"STFR.TShirt_Sheriff_Jefferson_CPT", 7,
			"STFR.Necklace_Badge_Sheriff_Jefferson_Gold", 8,
			"STFR.Necklace_Badge_Sheriff_Jefferson_Gold", 8,
			"STFR.Necklace_Badge_Sheriff_Jefferson_Gold", 8,
			"STFR.Necklace_Badge_Sheriff_Jefferson_Gold", 8,
			"STFR.Trousers_Sheriff_Jefferson", 6,
			"STFR.Tie_Full_Sheriff_Jefferson", 2,
			"STFR.Tie_Worn_Sheriff_Jefferson", 2,
			"STFR.Belt_Police_Duty", 2,
			"STFR.Chest_Walkie", 2,
			"STFR.Vest_BulletPolice_Meade", 1,
		},
		junk = {
			rolls = 1,
			items = {
			
			}
		}
	}

	ProceduralDistributions.list.LockerSheriffJeffersonSWAT = {
		rolls = 16,
		items = {
			"Disc_Retail", 2,
			"Earbuds", 1,
			"Headphones", 1,
			"Radio.CDplayer", 2,
			"Lunchbox", 1,
			"Lunchbox2", 1,
			"Glasses_Aviators", 1,
			"Nightstick", 2,
			"Radio.WalkieTalkie4", 1,
			"Shoes_ArmyBoots", 6,
			"Shoes_ArmyBoots", 6,
			"STFR.Hat_Balaclava_SWAT_Face", 1,
			"STFR.STFR_Hat_Balaclava_SWAT_Full", 1,
			"STFR.Glasses_SafetyGoggles_SWAT_Black", 1,
			"STFR.Bag_DuffelBag_Sheriff_Jefferson_SWAT_Green", 0.5,
			"STFR.Bag_DuffelBag_Sheriff_Jefferson_SWAT_Green", 0.5,
			"STFR.Alicepack_Sheriff_Jefferson_SWAT_Green", 0.5,
			"STFR.Helmet_Sheriff_Jefferson_Officer_SWAT_Green", 1.5,
			"STFR.Helmet_Sheriff_Jefferson_Officer_SWAT_Green", 1.5,
			"STFR.Gloves_Riot_Leather_Black", 2,
			"STFR.Gloves_Riot_Leather_Brown", 2,
			"STFR.Vest_Tactical_Sheriff_Jefferson_SWAT_Green", 1,
			"STFR.Vest_Tactical_Sheriff_Jefferson_SWAT_Green", 1,
			"STFR.Vest_BulletSheriff_Jefferson_SWAT_Green", 1,
			"STFR.Hat_BonnieHat_Sheriff_Jefferson_Officer_SWAT_Green", 4,
			"STFR.Hat_BaseballCap_Sheriff_Jefferson_Officer_SWAT_Green", 4,
			"STFR.Hat_BaseballCap_Sheriff_Jefferson_Officer_SWAT_Green", 2,
			"STFR.Shirt_Sheriff_Jefferson_Officer_SWAT_Green", 10,
			"STFR.TShirt_Sheriff_Jefferson_Officer_SWAT_Green", 10,
			"STFR.Trousers_Sheriff_Jefferson_SWAT_Green", 8,
			"STFR.Belt_Police_Duty", 2,
			"STFR.Chest_Walkie", 2,
		},
		junk = {
			rolls = 1,
			items = {
			
			}
		}
	}

	ProceduralDistributions.list.LockerPoliceKSP = {
		rolls = 4,
		items = {
			"Disc_Retail", 2,
			"Earbuds", 1,
			"Headphones", 1,
			"Radio.CDplayer", 2,
			"Lunchbox", 1,
			"Lunchbox2", 1,
			"Glasses_Aviators", 1,
			"STFR.Hat_Crash_Helmet_Police_KSP", 1.5,
			"STFR.Trousers_Police_KSP_Summer_Crash", 2,
			"STFR.Trousers_Police_KSP_Winter_Crash", 2,
			"Hat_EarMuff_Protectors", 1,
			"Nightstick", 2,
			"Radio.WalkieTalkie4", 1,
			"Shoes_Black", 6,
			"Shoes_Brown", 6,
			"STFR.Hat_Riot_Helmet_Police_KSP", 1.5,
			"STFR.Gloves_Riot_Leather_Black", 2,
			"STFR.Gloves_Riot_Leather_Brown", 2,
			"STFR.Gloves_Dress_White", 1,
			"STFR.Jacket_Dress_Police_KSP_Officer", 2,
			"STFR.Jacket_Dress_Police_KSP_SGT", 1,
			"STFR.Jacket_Dress_Police_KSP_CPT", 1,
			"STFR.Vest_HighViz_Police_KSP", 2,
			"STFR.Vest_HighViz_Police_KSP", 2,
			"STFR.Vest_HighViz_Police_KSP", 2,
			"STFR.Bag_DuffelBag_Police_KSP", 1,
			"STFR.Hat_Police_KSP_Officer", 4,
			"STFR.Hat_Police_KSP_Officer", 3,
			"STFR.Hat_Police_KSP_Officer", 3,
			"STFR.Jacket_Police_KSP_Officer", 4,
			"STFR.Jacket_Police_KSP_SGT", 3,
			"STFR.Jacket_Police_KSP_CPT", 3,
			"STFR.Shirt_Police_KSP_Officer", 8,
			"STFR.Shirt_Police_KSP_SGT", 7,
			"STFR.Shirt_Police_KSP_CPT", 7,
			"STFR.TShirt_Police_KSP_Officer", 8,
			"STFR.TShirt_Police_KSP_SGT", 7,
			"STFR.TShirt_Police_KSP_CPT", 7,
			"STFR.Necklace_Badge_Police_KSP_Gold", 8,
			"STFR.Necklace_Badge_Police_KSP_Gold", 8,
			"STFR.Necklace_Badge_Police_KSP_Silver", 8,
			"STFR.Necklace_Badge_Police_KSP_Silver", 8,
			"STFR.Trousers_Police_KSP_Summer", 6,
			"STFR.Trousers_Police_KSP_Winter", 6,
			"STFR.Tie_Full_Police_KSP", 2,
			"STFR.Tie_Worn_Police_KSP", 2,
			"STFR.Belt_Police_Duty", 2,
			"STFR.Chest_Walkie", 2,
			"Vest_BulletPolice", 1,
		},
		junk = {
			rolls = 1,
			items = {
			
			}
		}
	}

	ProceduralDistributions.list.LockerPoliceKSPSWAT = {
		rolls = 16,
		items = {
			"Disc_Retail", 2,
			"Earbuds", 1,
			"Headphones", 1,
			"Radio.CDplayer", 2,
			"Lunchbox", 1,
			"Lunchbox2", 1,
			"Glasses_Aviators", 1,
			"Nightstick", 2,
			"Radio.WalkieTalkie4", 1,
			"Shoes_ArmyBoots", 6,
			"Shoes_ArmyBoots", 6,
			"STFR.Hat_Balaclava_SWAT_Face", 1,
			"STFR.STFR_Hat_Balaclava_SWAT_Full", 1,
			"STFR.Glasses_SafetyGoggles_SWAT_Black", 1,
			"STFR.Bag_DuffelBag_Police_KSP_SWAT_Blue", 0.5,
			"STFR.Bag_DuffelBag_Police_KSP_SWAT_Blue", 0.5,
			"STFR.Alicepack_Police_KSP_SWAT_Black", 0.5,
			"STFR.Hat_Helmet_Police_KSP_Officer_SWAT_Black", 1.5,
			"STFR.Hat_Helmet_Police_KSP_Officer_SWAT_Black", 1.5,
			"STFR.Gloves_Riot_Leather_Black", 2,
			"STFR.Gloves_Riot_Leather_Brown", 2,
			"STFR.Vest_Tactical_Police_KSP_SWAT_Black", 1,
			"STFR.Vest_Tactical_Police_KSP_SWAT_Black", 1,
			"STFR.Vest_BulletPolice_KSP_SWAT_Black", 1,
			"STFR.Hat_BonnieHat_Police_KSP_Officer_SWAT_Blue", 4,
			"STFR.Hat_BonnieHat_Police_KSP_Officer_SWAT_Camo", 4,
			"STFR.Hat_BaseballCap_Police_KSP_Officer_SWAT_Blue", 4,
			"STFR.Hat_BaseballCap_Police_KSP_Officer_SWAT_Camo", 4,
			"STFR.Shirt_Police_KSP_Officer_SWAT_Blue", 10,
			"STFR.Shirt_Police_KSP_Officer_SWAT_Camo", 10,
			"STFR.TShirt_Police_KSP_Officer_SWAT_Blue", 10,
			"STFR.TShirt_Police_KSP_Officer_SWAT_Camo", 10,
			"STFR.Trousers_Police_KSP_SWAT_Blue", 8,
			"STFR.Trousers_Police_KSP_SWAT_Camo", 8,
			"STFR.Belt_Police_Duty", 2,
			"STFR.Chest_Walkie", 2,
		},
		junk = {
			rolls = 1,
			items = {
			
			}
		}
	}

	ProceduralDistributions.list.LaundryInmateMeade = {
		rolls = 1,
		items = {
			"STFR.Boilersuit_Meade_Gen_Pop_Prisoner", 50,
			"STFR.Boilersuit_Meade_Gen_Pop_Prisoner", 40,
			"STFR.Boilersuit_Meade_Low_Risk_Prisoner", 15,
			"STFR.Boilersuit_Meade_Low_Risk_Prisoner", 15,
			"STFR.Boilersuit_Meade_Supermax_Prisoner", 10,
			"STFR.Boilersuit_Meade_Supermax_Prisoner", 10,

		},
		junk = {
			rolls = 1,
			items = {
			
			}
		}
	}

	ProceduralDistributions.list.PrisonCellInmateMeade = {
		rolls = 4,
		items = {
			"Antibiotics", 0.25,
			"Bandage", 0.25,
			"Radio.CDplayer", 1,
			"Cereal", 4,
			"Chocolate", 4,
			"CordlessPhone", 0.01,
			"Crisps", 10,
			"HottieZ", 0.01,
			"Magazine", 10,
			"Newspaper", 10,
			"Notebook", 10,
			"Pencil", 10,
			"Pills", 0.5,
			"Radio.RadioBlack", 1,
			"Ramen", 10,
			"SheetPaper2", 20,
			"Teabag2", 6,
			"TunaTin", 4,
			"WhiskeyFull", 0.01,
		},
		junk = {
			rolls = 1,
			items = {
				"BathTowel", 20,
				"STFR.Boilersuit_Meade_Gen_Pop_Prisoner", 80,
				"STFR.Boilersuit_Meade_Low_Risk_Prisoner", 40,
				"Bowl", 10,
				"ButterKnife", 0.05,
				"Cigarettes", 8,
				"Comb", 4,
				"Crayons", 8,
				"Doll", 4,
				"KitchenKnife", 0.01,
				"Lighter", 4,
				"Matches", 8,
				"Mirror", 8,
				"Mugl", 4,
				"MugRed", 4,
				"MugWhite", 4,
				"Shoes_FlipFlop", 6,
				"Soap2", 10,
				"Socks_Ankle", 4,
				"Spiffo", 0.001,
				"Spoon", 20,
				"Toothbrush", 10,
				"Toothpaste", 10,
				"ToyBear", 4,
			}
		}
	}

	ProceduralDistributions.list.PrisonCellInmateMeadeSupermax = {
		rolls = 4,
		items = {
			"Antibiotics", 0.25,
			"Bandage", 0.25,
			"Radio.CDplayer", 1,
			"Cereal", 4,
			"Chocolate", 4,
			"CordlessPhone", 0.01,
			"Crisps", 10,
			"HottieZ", 0.01,
			"Magazine", 10,
			"Newspaper", 10,
			"Notebook", 10,
			"Pencil", 10,
			"Pills", 0.5,
			"Radio.RadioBlack", 1,
			"Ramen", 10,
			"SheetPaper2", 20,
			"Teabag2", 6,
			"TunaTin", 4,
			"WhiskeyFull", 0.01,
		},
		junk = {
			rolls = 1,
			items = {
				"BathTowel", 20,
				"STFR.Boilersuit_Meade_Supermax_Prisoner", 80,
				"Bowl", 10,
				"ButterKnife", 0.05,
				"Cigarettes", 8,
				"Comb", 4,
				"Crayons", 8,
				"Doll", 4,
				"KitchenKnife", 0.01,
				"Lighter", 4,
				"Matches", 8,
				"Mirror", 8,
				"Mugl", 4,
				"MugRed", 4,
				"MugWhite", 4,
				"Shoes_FlipFlop", 6,
				"Soap2", 10,
				"Socks_Ankle", 4,
				"Spiffo", 0.001,
				"Spoon", 20,
				"Toothbrush", 10,
				"Toothpaste", 10,
				"ToyBear", 4,
			}
		}
	}

	ProceduralDistributions.list.LockerDOCMeade = {
		rolls = 4,
		items = {
			"Disc_Retail", 2,
			"Earbuds", 1,
			"Headphones", 1,
			"Radio.CDplayer", 2,
			"Lunchbox", 1,
			"Lunchbox2", 1,
			"Glasses_Aviators", 1,
			"HolsterDouble", 0.5,
			"HolsterSimple", 2,
			"Nightstick", 2,
			"Radio.WalkieTalkie4", 1,
			"Radio.WalkieTalkie5", 0.5,
			"Shoes_Black", 8,
			"Shoes_Brown", 8,
			"STFR.Hat_BaseballCap_DOC_Meade", 4,
			"STFR.Jacket_DOC_Meade", 4,
			"STFR.Shirt_DOC_Meade", 10,
			"STFR.TShirt_DOC_Meade", 10,
			"STFR.Trousers_DOC_Meade", 10,
			"STFR.Belt_Police_Duty", 2,
			"STFR.Chest_Walkie", 2,
		},
		junk = {
			rolls = 1,
			items = {
			
			}
		}
	}

	ProceduralDistributions.list.LaundryInmateJefferson = {
		rolls = 1,
		items = {
			"STFR.Boilersuit_Jefferson_Prisoner", 50,
			"STFR.Boilersuit_Jefferson_Prisoner", 40,
		},
		junk = {
			rolls = 1,
			items = {
			
			}
		}
	}

	ProceduralDistributions.list.PrisonCellInmateJefferson = {
		rolls = 4,
		items = {
			"Antibiotics", 0.25,
			"Bandage", 0.25,
			"Radio.CDplayer", 1,
			"Cereal", 4,
			"Chocolate", 4,
			"CordlessPhone", 0.01,
			"Crisps", 10,
			"HottieZ", 0.01,
			"Magazine", 10,
			"Newspaper", 10,
			"Notebook", 10,
			"Pencil", 10,
			"Pills", 0.5,
			"Radio.RadioBlack", 1,
			"Ramen", 10,
			"SheetPaper2", 20,
			"Teabag2", 6,
			"TunaTin", 4,
			"WhiskeyFull", 0.01,
		},
		junk = {
			rolls = 1,
			items = {
				"BathTowel", 20,
				"STFR.Boilersuit_Jefferson_Prisoner", 80,
				"Bowl", 10,
				"ButterKnife", 0.05,
				"Cigarettes", 8,
				"Comb", 4,
				"Crayons", 8,
				"Doll", 4,
				"KitchenKnife", 0.01,
				"Lighter", 4,
				"Matches", 8,
				"Mirror", 8,
				"Mugl", 4,
				"MugRed", 4,
				"MugWhite", 4,
				"Shoes_FlipFlop", 6,
				"Soap2", 10,
				"Socks_Ankle", 4,
				"Spiffo", 0.001,
				"Spoon", 20,
				"Toothbrush", 10,
				"Toothpaste", 10,
				"ToyBear", 4,
			}
		}
	}

	ProceduralDistributions.list.LockerFireRosewood = {
		rolls = 4,
		items = {
			"Bag_FannyPackFront", 0.8,
			"Belt2", 2,
			"Disc_Retail", 2,
			"Earbuds", 1,
			"Glasses_Aviators", 1,
			"Hat_GasMask", 0.5,
			"Headphones", 1,
			"Lunchbox", 1,
			"Lunchbox2", 1,
			"Radio.CDplayer", 2,
			"Radio.WalkieTalkie4", 1,
			"Shoes_ArmyBoots", 4,
			"Shoes_ArmyBoots", 4,
			"Socks_Ankle", 8,
			"Socks_Long", 6,
			"STFR.Gloves_Dress_White", 1,
			"STFR.Trousers_Fire_Formal_Rosewood", 3,
			"STFR.Shirt_Fire_Rosewood", 2,
			"STFR.TShirt_Fire_Rosewood", 2,
			"STFR.Shirt_Fire_Rosewood_Supervisor", 2,
			"STFR.TShirt_Fire_Rosewood_Supervisor", 2,
			"STFR.Bag_DuffelBag_Fire_Black", 0.5,
			"STFR.Bag_DuffelBag_Fire_Khaki", 0.5,
			"STFR.Gloves_Fireman_Khaki", 2,
			"STFR.Gloves_Fireman_Khaki_Simple", 2,
			"STFR.Gloves_Fireman_Black", 2,
			"STFR.Gloves_Fireman_Black_Simple", 2,
			"STFR.Hat_Fireman_Rosewood_White", 2,
			"STFR.Hat_Fireman_Rosewood_Black", 2,
			"STFR.Hat_Fireman_Rosewood_Red", 2,
			"STFR.Hat_Fireman_Rosewood_Yellow", 2,
			"STFR.Jacket_Fireman_Black_Rosewood", 4,
			"STFR.Jacket_Fireman_Khaki_Rosewood", 4,
			"STFR.Trousers_Fireman_Black_Rosewood", 6,
			"STFR.Trousers_Fireman_Khaki_Rosewood", 6,
			"STFR.TShirt_Profession_Fireman_Blue_Rosewood", 6,
			"STFR.TShirt_Profession_Fireman_Red_Rosewood", 6,
			"STFR.TShirt_Profession_Fireman_Red_Rosewood02", 6,
			"STFR.TShirt_Profession_Fireman_White_Rosewood", 6,
		},
		junk = {
			rolls = 1,
			items = {
			
			}
		}
	}

	ProceduralDistributions.list.LockerFireLouisville = {
		rolls = 4,
		items = {
			"Bag_FannyPackFront", 0.8,
			"Belt2", 2,
			"Disc_Retail", 2,
			"Earbuds", 1,
			"Glasses_Aviators", 1,
			"Hat_GasMask", 0.5,
			"Headphones", 1,
			"Lunchbox", 1,
			"Lunchbox2", 1,
			"Radio.CDplayer", 2,
			"Radio.WalkieTalkie4", 1,
			"Shoes_ArmyBoots", 4,
			"Shoes_ArmyBoots", 4,
			"Socks_Ankle", 8,
			"Socks_Long", 6,
			"STFR.Gloves_Dress_White", 1,
			"STFR.Tie_Full_Fire_Louisville", 0.5,
			"STFR.Tie_Worn_Fire_Louisville", 0.5,
			"STFR.Hat_Fire_Louisville", 1,
			"STFR.Hat_Fire_Louisville_Supervisor_Black", 1,
			"STFR.Hat_Fire_Louisville_Supervisor_White", 2,
			"STFR.Trousers_Fire_Formal_Louisville", 3,
			"STFR.Shirt_Fire_Louisville_Supervisor_Station", 1,
			"STFR.TShirt_Fire_Louisville_Supervisor_Station", 1,
			"STFR.Shirt_Fire_Louisville_Supervisor", 2,
			"STFR.TShirt_Fire_Louisville_Supervisor", 2,
			"STFR.Shirt_Fire_Louisville", 2,
			"STFR.TShirt_Fire_Louisville", 2,
			"STFR.Bag_DuffelBag_Fire_Black", 0.5,
			"STFR.Bag_DuffelBag_Fire_Khaki", 0.5,
			"STFR.Gloves_Fireman_Khaki", 2,
			"STFR.Gloves_Fireman_Khaki_Simple", 2,
			"STFR.Gloves_Fireman_Black", 2,
			"STFR.Gloves_Fireman_Black_Simple", 2,
			"STFR.Hat_Fireman_Louisville_Blue", 2,
			"STFR.Hat_Fireman_Louisville_White", 2,
			"STFR.Hat_Fireman_Louisville_Black", 2,
			"STFR.Hat_Fireman_Louisville_Red", 2,
			"STFR.Hat_Fireman_Louisville_Yellow", 2,
			"STFR.Jacket_Fireman_Black_Louisville", 4,
			"STFR.Jacket_Fireman_Khaki_Louisville", 4,
			"STFR.Trousers_Fireman_Black_Louisville", 6,
			"STFR.Trousers_Fireman_Khaki_Louisville", 6,
			"STFR.TShirt_Profession_Fireman_Blue_Louisville", 8,
			"STFR.TShirt_Profession_Fireman_Red_Louisville", 8,
			"STFR.TShirt_Profession_Fireman_Red_Louisville02", 8,
			"STFR.TShirt_Profession_Fireman_White_Louisville", 8,
		},
		junk = {
			rolls = 1,
			items = {
			
			}
		}
	}

	ProceduralDistributions.list.LockerEMSMeade = {
		rolls = 16,
		items = {
			"Bag_FannyPackFront", 0.8,
			"Bag_Satchel", 0.2,
			"Belt2", 2,
			"Disc_Retail", 2,
			"Earbuds", 1,
			"Headphones", 1,
			"Lunchbox", 1,
			"Lunchbox2", 1,
			"Radio.CDplayer", 2,
			"Shoes_Random", 2,
			"Shoes_TrainerTINT", 2,
			"Socks_Ankle", 1,
			"Socks_Ankle", 1,
			"Socks_Long", 0.5,
			"STFR.Gloves_Dress_White", 1,
			"STFR.Tie_Full_EMS_Meade", 0.5,
			"STFR.Tie_Worn_EMS_Meade", 0.5,
			"STFR.Hat_EMS_Meade", 1,
			"STFR.Jacket_Dress_EMS_Meade", 2,
			"STFR.Bag_DuffelBag_EMS_Red", 0.5,
			"STFR.Bag_DuffelBag_EMS_Blue", 0.5,
			"STFR.Bag_DuffelBag_EMS_Green", 0.5,
			"STFR.Hat_BaseballCap_EMS_Meade", 4,
			"STFR.Jacket_EMS_Meade", 4,
			"STFR.Shirt_EMS_Meade", 10,
			"STFR.TShirt_EMS_Meade", 10,
			"STFR.Trousers_EMS_Meade", 8,
		},
		junk = {
			rolls = 1,
			items = {

			}
		}
	}

	ProceduralDistributions.list.LockerEMSLouisville = {
		rolls = 16,
		items = {
			"Bag_FannyPackFront", 0.8,
			"Bag_Satchel", 0.2,
			"Belt2", 2,
			"Disc_Retail", 2,
			"Earbuds", 1,
			"Headphones", 1,
			"Lunchbox", 1,
			"Lunchbox2", 1,
			"Radio.CDplayer", 2,
			"Shoes_Random", 2,
			"Shoes_TrainerTINT", 2,
			"Socks_Ankle", 1,
			"Socks_Ankle", 1,
			"Socks_Long", 0.5,
			"STFR.Gloves_Dress_White", 1,
			"STFR.Tie_Full_EMS_Louisville", 0.5,
			"STFR.Tie_Worn_EMS_Louisville", 0.5,
			"STFR.Hat_EMS_Louisville", 1,
			"STFR.Jacket_Dress_EMS_Louisville", 2,
			"STFR.Bag_DuffelBag_EMS_Red", 0.5,
			"STFR.Bag_DuffelBag_EMS_Blue", 0.5,
			"STFR.Bag_DuffelBag_EMS_Green", 0.5,
			"STFR.Hat_BaseballCap_EMS_Louisville", 4,
			"STFR.Jacket_EMS_Louisville", 4,
			"STFR.Shirt_EMS_Louisville", 10,
			"STFR.TShirt_EMS_Louisville", 10,
			"STFR.Trousers_EMS_Louisville", 8,
		},
		junk = {
			rolls = 1,
			items = {

			}
		}
	}

	ProceduralDistributions.list.LockerEMSJefferson = {
		rolls = 16,
		items = {
			"Bag_FannyPackFront", 0.8,
			"Bag_Satchel", 0.2,
			"Belt2", 2,
			"Disc_Retail", 2,
			"Earbuds", 1,
			"Headphones", 1,
			"Lunchbox", 1,
			"Lunchbox2", 1,
			"Radio.CDplayer", 2,
			"Shoes_Random", 2,
			"Shoes_TrainerTINT", 2,
			"Socks_Ankle", 1,
			"Socks_Ankle", 1,
			"Socks_Long", 0.5,
			"STFR.Gloves_Dress_White", 1,
			"STFR.Tie_Full_EMS_Jefferson", 0.5,
			"STFR.Tie_Worn_EMS_Jefferson", 0.5,
			"STFR.Hat_EMS_Jefferson", 1,
			"STFR.Jacket_Dress_EMS_Jefferson", 2,
			"STFR.Bag_DuffelBag_EMS_Red", 0.5,
			"STFR.Bag_DuffelBag_EMS_Blue", 0.5,
			"STFR.Bag_DuffelBag_EMS_Green", 0.5,
			"STFR.Hat_BaseballCap_EMS_Jefferson", 4,
			"STFR.Jacket_EMS_Jefferson", 4,
			"STFR.Shirt_EMS_Jefferson", 10,
			"STFR.TShirt_EMS_Jefferson", 10,
			"STFR.Trousers_EMS_Jefferson", 8,
		},
		junk = {
			rolls = 1,
			items = {

			}
		}
	}

	ProceduralDistributions.list.LockerUSPS = {
		rolls = 8,
		items = {
			"Bag_FannyPackFront", 0.6,
			"Belt2", 2,
			"Briefcase", 0.1,
			"Disc_Retail", 2,
			"Earbuds", 1,
			"Headphones", 1,
			"Lunchbox", 1,
			"Lunchbox2", 1,
			"Radio.CDplayer", 2,
			"Shoes_Random", 2,
			"Shoes_TrainerTINT", 2,
			"Socks_Ankle", 1,
			"Socks_Ankle", 1,
			"Socks_Long", 0.5,
			"Suitcase", 0.1,
			"STFR.Bag_DuffelBag_USPS", 2,
			"STFR.Tie_Full_Extra_USPS", 0.5,
			"STFR.Tie_Worn_Extra_USPS", 0.5,
			"STFR.Hat_BaseballCap_USPS", 4,
			"STFR.Jacket_USPS", 4,
			"STFR.Shirt_USPS", 8,
			"STFR.TShirt_USPS", 8,
			"STFR.Trousers_USPS", 6,
			"STFR.Shorts_USPS", 6,
			"STFR.Shorts_Short_USPS", 6,
			"STFR.Bag_Satchel_USPS", 4,
		},
		junk = {
			rolls = 1,
			items = {

			}
		}
	}

	ProceduralDistributions.list.LockerMallGrandOhio = {
		rolls = 16,
		items = {
			"Bag_FannyPackFront", 0.8,
			"Bag_Satchel", 0.2,
			"Belt2", 2,
			"Briefcase", 0.2,
			"Disc_Retail", 2,
			"Earbuds", 1,
			"Headphones", 1,
			"HolsterDouble", 0.5,
			"HolsterSimple", 2,
			"Lunchbox", 1,
			"Lunchbox2", 1,
			"Nightstick", 2,
			"Radio.CDplayer", 2,
			"Radio.WalkieTalkie4", 1,
			"HandTorch", 1,
			"Shoes_Black", 6,
			"Shoes_Brown", 6,
			"Suitcase", 0.2,
			"STFR.Hat_Security_Mall_Grand_Ohio", 3,
			"STFR.Jacket_Security_Mall_Grand_Ohio", 3,
			"STFR.Shirt_Security_Mall_Grand_Ohio", 6,
			"STFR.TShirt_Security_Mall_Grand_Ohio", 6,
			"STFR.Trousers_Security_Mall_Grand_Ohio", 4,
			"STFR.Tie_Full_Security_Mall_Grand_Ohio", 2,
			"STFR.Tie_Worn_Security_Mall_Grand_Ohio", 2,
			"STFR.Belt_Police_Duty", 2,
		},
		junk = {
			rolls = 1,
			items = {
			
			}
		}
	}

	ProceduralDistributions.list.LockerMallValleyStation = {
		rolls = 16,
		items = {
			"Bag_FannyPackFront", 0.8,
			"Bag_Satchel", 0.2,
			"Belt2", 2,
			"Briefcase", 0.2,
			"Disc_Retail", 2,
			"Earbuds", 1,
			"Headphones", 1,
			"HolsterDouble", 0.5,
			"HolsterSimple", 2,
			"Lunchbox", 1,
			"Lunchbox2", 1,
			"Nightstick", 2,
			"Radio.CDplayer", 2,
			"Radio.WalkieTalkie4", 1,
			"HandTorch", 1,
			"Shoes_Black", 6,
			"Shoes_Brown", 6,
			"Suitcase", 0.2,
			"STFR.Hat_Security_Mall_Valley_Station", 3,
			"STFR.Jacket_Security_Mall_Valley_Station", 3,
			"STFR.Shirt_Security_Mall_Valley_Station", 6,
			"STFR.TShirt_Security_Mall_Valley_Station", 6,
			"STFR.Trousers_Security_Mall_Valley_Station", 4,
		},
		junk = {
			rolls = 1,
			items = {
			
			}
		}
	}

	ProceduralDistributions.list.AllMetalShelves = {
		rolls = 16,
		items = {
			"BallPeenHammer", 0.6,
			"Battery", 1,
			"BucketEmpty", 0.4,
			"ClubHammer", 0.4,
			"Crowbar", 0.4,
			"DuctTape", 0.8,
			"Glasses_SafetyGoggles", 0.2,
			"Hammer", 0.6,
			"HandAxe", 0.1,
			"HandTorch", 0.4,
			"Hat_DustMask", 0.2,
			"Hat_HardHat", 0.1,
			"LeadPipe", 0.4,
			"LeadPipe", 0.4,
			"MetalBar", 1.2,
			"MetalPipe", 2,
			"Nails", 4,
			"NailsBox", 1,
			"PipeWrench", 0.4,
			"Radio.ElectricWire", 0.5,
			"Radio.RadioBlack", 2,
			"Radio.RadioRed", 1,
			"Radio.WalkieTalkie1", 0.05,
			"Radio.WalkieTalkie2", 0.03,
			"Radio.WalkieTalkie3", 0.01,
			"Rope", 0.8,
			"Saw", 0.4,
			"Screwdriver", 1,
			"ScrewsBox", 0.4,
			"SheetMetal", 2,
			"Shovel", 0.4,
			"Shovel2", 0.4,
			"SmallSheetMetal", 1,
			"Tarp", 1,
			"Toolbox", 0.5,
			"Torch", 0.2,
			"Twine", 1,
			"WeldingMask", 0.2,
			"WeldingRods", 1,
			"Wire", 0.8,
			"WoodenMallet", 0.4,
			"Woodglue", 0.4,
			"Wrench", 0.6,
		},
		junk = {
			rolls = 1,
			items = {

			}
		}
	}

	ProceduralDistributions.list.AllCrate = {
		rolls = 1,
		items = {
			"Axe", 0.005,
			"BallPeenHammer", 0.6,
			"BarbedWire", 0.2,
			"Battery", 1,
			"BlowTorch", 0.8,
			"BucketEmpty", 0.4,
			"camping.TentPeg", 2,
			"Charcoal", 0.05,
			"ClubHammer", 0.4,
			"ConcretePowder", 2,
			"Crowbar", 0.4,
			"DuctTape", 0.8,
			"EmptySandbag", 0.2,
			"farming.BroccoliBagSeed", 0.8,
			"farming.CabbageBagSeed", 0.8,
			"farming.CarrotBagSeed", 0.8,
			"farming.GardeningSprayEmpty", 0.6,
			"farming.HandShovel", 1,
			"farming.PotatoBagSeed", 0.8,
			"farming.RedRadishBagSeed", 0.8,
			"farming.StrewberrieBagSeed", 0.8,
			"farming.TomatoBagSeed", 0.8,
			"farming.WateredCan", 0.6,
			"Fertilizer", 2,
			"GardenFork", 0.1,
			"GardenHoe", 0.2,
			"GardenSaw", 0.6,
			"Glasses_SafetyGoggles", 0.2,
			"Gravelbag", 2,
			"Hammer", 0.6,
			"HandAxe", 0.1,
			"HandFork", 0.2,
			"HandScythe", 0.2,
			"HandTorch", 0.4,
			"Hat_DustMask", 0.2,
			"Hat_HardHat", 0.1,
			"Jack", 0.2,
			"LeadPipe", 0.4,
			"LeafRake", 1,
			"Lighter", 4,
			"LugWrench", 0.9,
			"MetalBar", 1.2,
			"MetalPipe", 2,
			"NailsBox", 1,
			"NailsBox", 1,
			"NailsBox", 1,
			"NailsBox", 1,
			"PaintBlack", 0.8,
			"PaintBlue", 0.8,
			"PaintBrown", 0.8,
			"Paintbrush", 0.4,
			"PaintCyan", 0.8,
			"PaintGreen", 0.8,
			"PaintGrey", 0.8,
			"PaintLightBlue", 0.8,
			"PaintLightBrown", 0.8,
			"PaintOrange", 0.8,
			"PaintPink", 0.8,
			"PaintPurple", 0.8,
			"PaintRed", 0.8,
			"PaintTurquoise",0.8,
			"PaintWhite", 0.8,
			"PaintYellow", 0.8,
			"Paperclip", 0.8,
			"PaperclipBox", 0.5,
			"PickAxe", 0.05,
			"PipeWrench", 0.4,
			"Plank", 1,
			"Plank", 1,
			"PlasterPowder", 2,
			"PropaneTank", 0.05,
			"Radio.ElectricWire", 0.5,
			"Radio.HamRadio1", 0.005,
			"Radio.RadioBlack", 2,
			"Radio.RadioRed", 1,
			"Radio.WalkieTalkie1", 0.05,
			"Radio.WalkieTalkie2", 0.03,
			"Radio.WalkieTalkie3", 0.01,
			"Rake", 1,
			"Rope", 0.8,
			"Sandbag", 0.5,
			"Saw", 0.4,
			"Screwdriver", 1,
			"ScrewsBox", 0.4,
			"SheetMetal", 2,
			"Shovel", 0.4,
			"Shovel2", 0.4,
			"Sledgehammer", 0.001,
			"Sledgehammer2", 0.001,
			"SmallSheetMetal", 1,
			"Tarp", 1,
			"TirePump", 0.6,
			"Torch", 0.2,
			"Twine", 1,
			"WeldingMask", 0.2,
			"WeldingRods", 1,
			"Wire", 0.8,
			"WoodAxe", 0.0025,
			"WoodenMallet", 0.4,
			"Woodglue", 0.4,
			"Wrench", 0.6,
		},
		junk = {
			rolls = 1,
			items = {

			}
		}
	}

end

Events.OnPreDistributionMerge.Add(STFRPreDistributionMerge);